name: ext-swoole_postgresql

on: [push, pull_request]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install-swoole
      run: sudo apt install -y php-dev php-pecl-http php-pecl-http-dev && pecl install swoole
    - name: phpize
      run: phpize
    - name: build
      run: ./configure && make clean && make -j$(sysctl -n hw.ncpu)

